### ISSUE TITLE
Arduino send MAC with only one 0

### ISSUE THREAD

**Issue by PcTim** [powtac/Autarc_LAN_User_Stats#54]
The arduino shield shold send the MAC decoded with two Octets. 0 at the beginning is single.

**Comment by powtac** [comment]
@PcTim what is the status of this problem? Solved?

**Comment by PcTim** [comment]
I'm not sure, I'll check it

**Comment by PcTim** [comment]
Problem still there.
<code>
void leading_zero_mac(char* return_mac, byte* mac) {
  sprintf(return_mac, "%02X:%02X:%02X:%02X:%02X:%02X", mac[0], mac[1], mac[2], mac[3], mac[4], mac[5]); 
}
</code>
Would help us, but needs to much memory because of sprintf. So I'll try another version...
