### ISSUE TITLE
New paradigm - for when to store Pings on the server

### ISSUE THREAD

**Issue by powtac** [powtac/Autarc_LAN_User_Stats#55]
1. Every single Ping is stored.
2. Only on every success Ping the current "Batch" is transmitted to the server (Batch = all previous inactive Pings + the current success Ping). Then the "Batch" is reseted on the scanner.

![foto 22 03 15 19 52 27](https://cloud.githubusercontent.com/assets/36167/6780816/ad8d965e-d168-11e4-8148-383d78940ccc.jpg)

**Comment by PcTim** [comment]
Implemented since 8e9989ddd40feeab39fb5bbc35a6a12c79a266a4, but not checked yet...

**Comment by PcTim** [comment]
fixed 319fa32353c6470ae6784a399f019782862eccd3
