### ISSUE TITLE
Form to store network name

### ISSUE THREAD

**Issue by powtac** [powtac/Autarc_LAN_User_Stats#57]
We need a HTML form to store the network name. Default the Mac of the scanner will be the network name.

**Comment by powtac** [comment]
Form:

Set a name for your network [    ] [Save]

**Comment by PcTim** [comment]
Isn't the AVR-ID used yet instead of the Mac?
Why do you want to set up the network name in the HTML form but the other configurations only with the serial monitor?
Or should we add some configurations to both of them? See #35

**Comment by powtac** [comment]
You are correct! This can be done via the serial monitor! 

This ticket will be closed in favor of #35.
