### ISSUE TITLE
Server doesn't accept data

### ISSUE THREAD

**Issue by PcTim** [powtac/Autarc_LAN_User_Stats#58]
The server doesn't accept "Content-Type: application/json;" from the arduino.
Also we may have problems with the ? in the servers-path.

The server returns only a 403 Forbidden error.
I think the servers mod security doesn't allow POST data within a request, but I'm not sure. Powtac, could you post the servers access data, please?

**Comment by PcTim** [comment]
I've tried in different combinations:
"Content-Type: application/json;"
"Content-Type: application/x-www-form-urlencoded;"
"Content-Type: application/x-www-form-urlencoded; charset=UTF-8;"
"X-Requested-With: XMLHttpRequest"

...but all without having success

**Comment by PcTim** [comment]
Also I've tried it with dummy data and calculated Content-Length the whole time. It only succeed in getting no 408 Request-Time-Out error.

**Comment by powtac** [comment]
I changed the server, please try again.

**Comment by PcTim** [comment]
Seems good! I get a response! Now I've to look why the data won't be stored, but shouldn't be that problem...

**Comment by powtac** [comment]
When you printout the debug info of the response of the server, can you print out the URL as well? I do test it now as well with my hardware...
