### ISSUE TITLE
Same Mac address used by two different IP addresses

### ISSUE THREAD

**Issue by powtac** [powtac/Autarc_LAN_User_Stats#64]
This is probably a bug in the code, the Mac Address is not filled correctly in the second case...
![unbenannt](https://cloud.githubusercontent.com/assets/36167/8024948/f11fce64-0d45-11e5-8b36-462fd5665808.PNG)

**Comment by PcTim** [comment]
Is it possible, that the device has changed its IP address during the scan. (Within 6 minutes it would be possible) also the board has had problems with the server connection as we can see in the time difference within the online device.

**Comment by PcTim** [comment]
Oh! Hm. Strange: IP .1.6 was scanned 19:30:09; IP .1.32 was scanned 19:33:15 - 186 seconds = 19:30:09

**Comment by PcTim** [comment]
Maybe a buffer problem...

**Comment by PcTim** [comment]
Have you had this problem twice?
Do you know if there truly was a device at both IPs? A had a suggestion, that there was a mistake in the ping libary. #63

**Comment by powtac** [comment]
> Have you had this problem twice?

Yes, the problem occurs several times in the log files!

**Comment by PcTim** [comment]
Already after the previous commit?

**Comment by powtac** [comment]
I will check it again with the latest version of code...

**Comment by PcTim** [comment]
Should be fixed since the b5097cc868c27b66dc830c5c379c6807074c4332 commit
