### ISSUE TITLE
Filesize too large

### ISSUE THREAD

**Issue by powtac** [powtac/Autarc_LAN_User_Stats#74]
Can't compile, filesize too large. Diabled SD Card and Serial debugging, but still 114% too large.

What can I do to get it locally run?

**Comment by PcTim** [comment]
Sorry for the late reply.
You can temporary change to commit 5f6ea5ab893abac03218b7d692ee3e66d366c012 and disable the SD log.
I will have a look at this.

**Comment by powtac** [comment]
Ist jetzt drin.

**Comment by powtac** [comment]
Ups, fälschlicherweise Jonas hinzugefügt.
