### ISSUE TITLE
String errors with Linux arduino version 2:1.0.5

### ISSUE THREAD

**Issue by PcTim** [powtac/Autarc_LAN_User_Stats#76]
A lot of string conversion errors in Linux Arduino Studio Version 2:1.0.5

**Comment by powtac** [comment]
:-/

**Comment by PcTim** [comment]
Maybe there's an old version at the software center. I'll try to install it manually...

**Comment by powtac** [comment]
I'm using always the latest Windows Version available for manual download on arduino.cc.

**Comment by PcTim** [comment]
The Linux version on arduino.cc seems much better as the one at the software center. But also a lot of errors. Mostly macro F and unescape sequence with backslash.
Do you have any errors with version 1.6.7?

**Comment by powtac** [comment]
Don't think so. Had only the problems with the overall size... No code errors.

**Comment by PcTim** [comment]
Strange...

**Comment by PcTim** [comment]
9188c9c97d34de8f1806e62365e5665afd3d52d7
